#ifndef REGISTER_OBJECT
#define REGISTER_OBJECT(EType,Class,Parent)
#endif
REGISTER_OBJECT(BearGraphics::GOT_ShaderResource, BearRenderShaderResourceBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_Texture2D,BearRenderTexture2DBase, BearRenderShaderResourceBase)
REGISTER_OBJECT(BearGraphics::GOT_RenderTargetView,BearRenderTargetViewBase, BearRenderShaderResourceBase)
REGISTER_OBJECT(BearGraphics::GOT_Viewport,BearRenderViewportBase,BearRenderTargetViewBase)
REGISTER_OBJECT(BearGraphics::GOT_Shader, BearRenderShaderBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_Pipeline, BearRenderPipelineBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_IndexBuffer,BearRenderIndexBufferBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_UniformBuffer, BearRenderUniformBufferBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_VertexBuffer, BearRenderVertexBufferBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_RootSignature, BearRenderRootSignatureBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_DescriptorHeap, BearRenderDescriptorHeapBase, BearRenderObject)
REGISTER_OBJECT(BearGraphics::GOT_SamplerState, BearRenderSamplerStateBase, BearRenderObject)
#undef REGISTER_OBJECT